### ISSUE TITLE
What about using new select menus instead of buttons for the searches?

### ISSUE THREAD

**Issue by Murky-MoMo** [Ayeven/generic-bot#6]
Currently this looks like this 
![](https://cdn.discordapp.com/attachments/805146894841806908/860140023528685618/unknown.png)
this is what it'd probably look like if menus were implemented instead
![](https://cdn.discordapp.com/attachments/805146894841806908/860140406019981322/unknown.png)
![](https://cdn.discordapp.com/attachments/805146894841806908/860140324668440576/unknown.png)

**Comment by Ayeven** [comment]
Have not look into the documentation/guide even for select menu. But surely does look better than ugly not `same size button(s). Will take a look and have a try on it

**Comment by Murky-MoMo** [comment]
so should i start working on a pull request for that?

**Comment by Ayeven** [comment]
I'm open for that. I like to have it select multiple song(s)/track actually since class `Playlist.queue` is basically an array, so it should be easy to `push it into it`, though still no idea to implement or even read or plan on it. Are you using the collection method or using it via event? Asking it since I'm using the `interaction event` instead of collection for some persistent after reboot.

**Comment by Murky-MoMo** [comment]
the screenshots i posted are from modifying the code here
and it would be easy to implement
(replace the buttons , instead of using `customID` for buttons, you need to use `value` for select menus)
and that'd be okay but the code i implemented it on was a previous version of the code where you were using collectors
i haven't checked out the new code yet

**Comment by Ayeven** [comment]
Just pushed some minor update removing tenor from configSchema, oversight from me after I cancelled adding tenor into bot feat.

**Comment by Murky-MoMo** [comment]
> Are you using the collection method or using it via event?

you mean collector? well no, since you've removed it, my plan was to not make it conflict with the existing code
I did implement it to the event on #7

**Comment by Ayeven** [comment]
[#7](https://github.com/Ayeven/generic-bot/pull/7 ) Have been merged, closing this issue
